name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-clj:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Setup Java 11"
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        lein: latest
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: "m2-${{ hashFiles('project.clj') }}"
    - name: Run tests
      run: lein test
    - name: Build uberjar
      run: lein uberjar
